2024-07-19 20:54:02,623 ERROR: Exception on / [GET] [in C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\flask\app.py:838]
Traceback (most recent call last):
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3300, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 914, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\event\attr.py", line 483, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\event\attr.py", line 497, in __call__
    fn(*args, **kw)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 721, in on_connect
    do_on_connect(dbapi_connection)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 778, in on_connect
    fn(dbapi_conn)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 753, in on_connect
    hstore_oids = self._hstore_oids(dbapi_conn)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1190, in oneshot
    result = fn(self, *args, **kw)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 829, in _hstore_oids
    oids = extras.HstoreAdapter.get_oids(dbapi_connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\psycopg2\extras.py", line 907, in get_oids
    curs.execute(f"""SELECT t.oid, {typarray}
psycopg2.OperationalError: SSL connection has been closed unexpectedly


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\flask\app.py", line 1473, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\flask\app.py", line 882, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\flask\app.py", line 880, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\flask\app.py", line 865, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)  # type: ignore[no-any-return]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\test\app\routes.py", line 7, in index
    entries = Entry.query.all()
              ^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2673, in all
    return self._iter().all()  # type: ignore
           ^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\orm\query.py", line 2827, in _iter
    result: Union[ScalarResult[_T], Result[_T]] = self.session.execute(
                                                  ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2351, in execute
    return self._execute_internal(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2226, in _execute_internal
    conn = self._connection_for_bind(bind)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 2095, in _connection_for_bind
    return trans._connection_for_bind(engine, execution_options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 2, in _connection_for_bind
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\orm\state_changes.py", line 139, in _go
    ret_value = fn(self, *arg, **kw)
                ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\orm\session.py", line 1189, in _connection_for_bind
    conn = bind.connect()
           ^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3276, in connect
    return self._connection_cls(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 148, in __init__
    Connection._handle_dbapi_exception_noconnection(
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 2440, in _handle_dbapi_exception_noconnection
    raise sqlalchemy_exception.with_traceback(exc_info[2]) from e
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 146, in __init__
    self._dbapi_connection = engine.raw_connection()
                             ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\base.py", line 3300, in raw_connection
    return self.pool.connect()
           ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 449, in connect
    return _ConnectionFairy._checkout(self)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 1263, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 712, in checkout
    rec = pool._do_get()
          ^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 179, in _do_get
    with util.safe_reraise():
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 146, in __exit__
    raise exc_value.with_traceback(exc_tb)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\impl.py", line 177, in _do_get
    return self._create_connection()
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 390, in _create_connection
    return _ConnectionRecord(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 674, in __init__
    self.__connect()
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\pool\base.py", line 914, in __connect
    )._exec_w_sync_on_first_run(self.dbapi_connection, self)
      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\event\attr.py", line 483, in _exec_w_sync_on_first_run
    self(*args, **kw)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\event\attr.py", line 497, in __call__
    fn(*args, **kw)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\engine\create.py", line 721, in on_connect
    do_on_connect(dbapi_connection)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 778, in on_connect
    fn(dbapi_conn)
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 753, in on_connect
    hstore_oids = self._hstore_oids(dbapi_conn)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\util\langhelpers.py", line 1190, in oneshot
    result = fn(self, *args, **kw)
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\sqlalchemy\dialects\postgresql\psycopg2.py", line 829, in _hstore_oids
    oids = extras.HstoreAdapter.get_oids(dbapi_connection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\paliw\Documents\YT Playlist\testing\Flask-App-With-Postgres-DB\venv\Lib\site-packages\psycopg2\extras.py", line 907, in get_oids
    curs.execute(f"""SELECT t.oid, {typarray}
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) SSL connection has been closed unexpectedly

(Background on this error at: https://sqlalche.me/e/20/e3q8)
